### ISSUE TITLE
Unable to run script, fails on Step 1

### ISSUE THREAD

**Issue by khouston6** [IIEleven11/Automatic-Audio-Dataset-Maker#1]
I tried to use this on both Windows and WSL2, but for some reason I am unable to get the code to transcribe the audio.

I follow the steps to get everything setup, move my raw audio files (I have tried both FLAC and WAV), then run the adm_main.py file, but get the following error each time:

```
Your HuggingFace Token env variable isn't set. It's ok, you can provide it here. Enter your Hugging Face access token:
Your Deepgram API key env variable isn't set. It's ok, you can provide it here. Enter your Deepgram API key:
Enter your Hugging Face username:
Enter the repository name:
Do you want to skip Step 1/2 (Transcribe and convert audio)? (y/n): n
Enter the SPEAKER_NAME: test
Enter the EVAL_PERCENTAGE (percentage of data to move to evaluation set): 10
Skipping Step 1: Transcribe audio
All segments have been processed and saved.
CSV file has been saved to F:\Automatic-Audio-Dataset-Maker\PARENT_CSV\metadata.csv
Moved 0 rows from F:\Automatic-Audio-Dataset-Maker\PARENT_CSV\metadata.csv to F:\Automatic-Audio-Dataset-Maker\METADATA\metadata_eval.csv
Generating train split: 0 examples [00:00, ? examples/s]
Traceback (most recent call last):
  File "F:\Automatic-Audio-Dataset-Maker\adm_main.py", line 394, in <module>
    asyncio.run(main())
  File "C:\Users\Kevin\anaconda3\envs\audiodatasetmaker\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Kevin\anaconda3\envs\audiodatasetmaker\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\Automatic-Audio-Dataset-Maker\adm_main.py", line 354, in main
    create_and_push_dataset(CSV_FILE_PATH, COMBINED_USERNAME_REPOID)
  File "F:\Automatic-Audio-Dataset-Maker\adm_main.py", line 229, in create_and_push_dataset
    dataset = DatasetDict.from_csv({"train": PARENT_CSV}, delimiter="|")
  File "C:\Users\Kevin\anaconda3\envs\audiodatasetmaker\lib\site-packages\datasets\dataset_dict.py", line 1367, in from_csv
    ).read()
  File "C:\Users\Kevin\anaconda3\envs\audiodatasetmaker\lib\site-packages\datasets\io\csv.py", line 63, in read
    dataset = self.builder.as_dataset(
  File "C:\Users\Kevin\anaconda3\envs\audiodatasetmaker\lib\site-packages\datasets\builder.py", line 1125, in as_dataset
    datasets = map_nested(
  File "C:\Users\Kevin\anaconda3\envs\audiodatasetmaker\lib\site-packages\datasets\utils\py_utils.py", line 511, in map_nested
    mapped = [
  File "C:\Users\Kevin\anaconda3\envs\audiodatasetmaker\lib\site-packages\datasets\utils\py_utils.py", line 512, in <listcomp>
    _single_map_nested((function, obj, batched, batch_size, types, None, True, None))
  File "C:\Users\Kevin\anaconda3\envs\audiodatasetmaker\lib\site-packages\datasets\utils\py_utils.py", line 373, in _single_map_nested
    return function(data_struct)
  File "C:\Users\Kevin\anaconda3\envs\audiodatasetmaker\lib\site-packages\datasets\builder.py", line 1155, in _build_single_dataset
    ds = self._as_dataset(
  File "C:\Users\Kevin\anaconda3\envs\audiodatasetmaker\lib\site-packages\datasets\builder.py", line 1229, in _as_dataset
    dataset_kwargs = ArrowReader(cache_dir, self.info).read(
  File "C:\Users\Kevin\anaconda3\envs\audiodatasetmaker\lib\site-packages\datasets\arrow_reader.py", line 251, in read
    raise ValueError(msg)
ValueError: Instruction "train" corresponds to no data!
```

**Comment by IIEleven11** [comment]
I'm going to push a commit that should fix this

**Comment by IIEleven11** [comment]
ok try that, the traceback does say that there is no audio in the folder though. So make sure its in the RAW_AUDIO folder like this.
![image](https://github.com/user-attachments/assets/92552007-d0de-44de-ba4d-c911d6b41796)

**Comment by IIEleven11** [comment]
closing this as solved. If you continue to have any problems please feel free to start a new issue post.
