### ISSUE TITLE
ValueError: Audio must have length greater than the block size.

### ISSUE THREAD

**Issue by Jinsaryko** [IIEleven11/Automatic-Audio-Dataset-Maker#3]
Came across this project and felt it was perfect for what I was planning on doing. Had some issues with it, but nothing that I couldn't get through with help from google and asking others. This morning, the transcription using whisper/deepgram stopped working for some reason, just gave an error that something went wrong during the process. Didn't mind that, as I wanted to use whisperx on my own to cut up the audio files myself. I put the cut wav files into predenoise folder and put the correct cvs files into their folder. Ran the program, everything went fine until I got to the denoise part and got this error:

Normalizing:  56%|████████████████████████████████████▋                            | 658/1165 [00:04<00:03, 136.26it/s]
Traceback (most recent call last):
  File "C:\Users\jinsa\anaconda3\envs\audiodatasetmaker\Automatic-Audio-Dataset-Maker-main\adm_main.py", line 515, in <module>
    asyncio.run(main())
  File "C:\Users\jinsa\anaconda3\envs\audiodatasetmaker\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\jinsa\anaconda3\envs\audiodatasetmaker\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\jinsa\anaconda3\envs\audiodatasetmaker\Automatic-Audio-Dataset-Maker-main\adm_main.py", line 466, in main
    denoise_and_normalize(WAVS_DIR_PREDENOISE, WAVS_DIR_POSTDENOISE, COMBINED_USERNAME_REPOID)
  File "C:\Users\jinsa\anaconda3\envs\audiodatasetmaker\Automatic-Audio-Dataset-Maker-main\adm_main.py", line 357, in denoise_and_normalize
    normalize_audio(input_file, output_file)
  File "C:\Users\jinsa\anaconda3\envs\audiodatasetmaker\Automatic-Audio-Dataset-Maker-main\tools\normalize_folder.py", line 20, in normalize_audio
    loudness = meter.integrated_loudness(audio)
  File "C:\Users\jinsa\anaconda3\envs\audiodatasetmaker\lib\site-packages\pyloudnorm\meter.py", line 55, in integrated_loudness
    util.valid_audio(input_data, self.rate, self.block_size)
  File "C:\Users\jinsa\anaconda3\envs\audiodatasetmaker\lib\site-packages\pyloudnorm\util.py", line 33, in valid_audio
    raise ValueError("Audio must have length greater than the block size.")
ValueError: Audio must have length greater than the block size.

This one stumped me, nothing on google showed how to fix this and I could not get any help from others. I even tried my luck with ChatGPT, but it wasn't much help. I made sure the audio files are in wav format, 16 bits and a sample_rate of 44100. Funny thing is, I tested an older file I had used before successfully and that went through for whatever reason. Same stats as the file that causes the error.  I may be missing some obvious. Well anyway, thanks for any help.

**Comment by IIEleven11** [comment]
Id assume one of your pieces of audio is short or potentially corrupted? It's hard to tell, if you can narrow it down to which file.

Although I just noticed you closed this, hopefully you pinpointed it
